/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Quicksand"', "ui-sans-serif", "system-ui", "sans-serif"],
        body: ['"Google Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
      colors: {
        brand: {
          primary: "rgb(var(--brand-primary) / <alpha-value>)",
          secondary: "rgb(var(--brand-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--brand-tertiary) / <alpha-value>)",
          onPrimary: "rgb(var(--on-brand-primary) / <alpha-value>)",
          onSecondary: "rgb(var(--on-brand-secondary) / <alpha-value>)",
          onTertiary: "rgb(var(--on-brand-tertiary) / <alpha-value>)",
          primaryContainer: "rgb(var(--brand-primary-container) / <alpha-value>)",
          secondaryContainer: "rgb(var(--brand-secondary-container) / <alpha-value>)",
          tertiaryContainer: "rgb(var(--brand-tertiary-container) / <alpha-value>)",
          onPrimaryContainer: "rgb(var(--on-brand-primary-container) / <alpha-value>)",
          onSecondaryContainer: "rgb(var(--on-brand-secondary-container) / <alpha-value>)",
          onTertiaryContainer: "rgb(var(--on-brand-tertiary-container) / <alpha-value>)",
          error: "rgb(var(--brand-error) / <alpha-value>)",
          onError: "rgb(var(--on-brand-error) / <alpha-value>)",
          errorContainer: "rgb(var(--brand-error-container) / <alpha-value>)",
          onErrorContainer: "rgb(var(--on-brand-error-container) / <alpha-value>)",
        },
        surface: {
          base: "rgb(var(--surface-base) / <alpha-value>)",
          dim: "rgb(var(--surface-dim) / <alpha-value>)",
          bright: "rgb(var(--surface-bright) / <alpha-value>)",
          soft: "rgb(var(--surface-soft) / <alpha-value>)",
          raised: "rgb(var(--surface-raised) / <alpha-value>)",
          variant: "rgb(var(--surface-variant) / <alpha-value>)",
          containerLowest: "rgb(var(--surface-container-lowest) / <alpha-value>)",
          containerLow: "rgb(var(--surface-container-low) / <alpha-value>)",
          container: "rgb(var(--surface-container) / <alpha-value>)",
          containerHigh: "rgb(var(--surface-container-high) / <alpha-value>)",
          containerHighest: "rgb(var(--surface-container-highest) / <alpha-value>)",
        },
        inverse: {
          surface: "rgb(var(--inverse-surface) / <alpha-value>)",
          onSurface: "rgb(var(--inverse-on-surface) / <alpha-value>)",
          primary: "rgb(var(--inverse-primary) / <alpha-value>)",
        },
        ink: {
          primary: "rgb(var(--ink-primary) / <alpha-value>)",
          muted: "rgb(var(--ink-muted) / <alpha-value>)",
          onSurfaceVariant: "rgb(var(--ink-on-surface-variant) / <alpha-value>)",
        },
        stroke: {
          subtle: "rgb(var(--stroke-subtle) / <alpha-value>)",
          outlineVariant: "rgb(var(--outline-variant) / <alpha-value>)",
        },
        scrim: "rgb(var(--scrim) / <alpha-value>)",
      },
      /* M3 Shape Scale */
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "28px",
        full: "9999px",
      },
      boxShadow: {
        "elevation-0": "none",
        "elevation-1": "0px 1px 2px 0px rgb(var(--shadow-color) / 0.3), 0px 1px 3px 1px rgb(var(--shadow-color) / 0.15)",
        "elevation-2": "0px 1px 2px 0px rgb(var(--shadow-color) / 0.3), 0px 2px 6px 2px rgb(var(--shadow-color) / 0.15)",
        "elevation-3": "0px 4px 8px 3px rgb(var(--shadow-color) / 0.15), 0px 1px 3px 0px rgb(var(--shadow-color) / 0.3)",
        "elevation-4": "0px 6px 10px 4px rgb(var(--shadow-color) / 0.15), 0px 2px 3px 0px rgb(var(--shadow-color) / 0.3)",
        "elevation-5": "0px 8px 12px 6px rgb(var(--shadow-color) / 0.15), 0px 4px 4px 0px rgb(var(--shadow-color) / 0.3)",
      },
      /* M3 Motion Easing */
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        "standard-accel": "cubic-bezier(0.3, 0, 1, 1)",
        "standard-decel": "cubic-bezier(0, 0, 0, 1)",
        emphasized: "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized-decel": "cubic-bezier(0.05, 0.7, 0.1, 1)",
        "emphasized-accel": "cubic-bezier(0.3, 0, 0.8, 0.15)",
      },
      /* M3 Motion Duration */
      transitionDuration: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
      },
      /* M3 4dp Base Grid Spacing */
      spacing: {
        0.5: "0.125rem",
        1: "0.25rem",
        1.5: "0.375rem",
        2: "0.5rem",
        3: "0.75rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        8: "2rem",
        10: "2.5rem",
        12: "3rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
      },
    },
  },
  plugins: [],
};
